/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪探针（检查 PostgreSQL 与 Redis） */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 账号密码登录
         * @description 用户名在租户内唯一。若同一用户名存在于多个租户，需传 `tenant_code`。连续失败 5 次锁定 15 分钟。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新令牌（refresh token 一次性轮换） */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录（吊销当前 access token，可选吊销 refresh token） */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户资料、权限码与菜单树 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户可见菜单树 */
        get: operations["getMenus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改本人密码（其余会话的 refresh token 失效） */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户列表 */
        get: operations["listUsers"];
        put?: never;
        /** 新建用户 */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** 用户详情 */
        get: operations["getUser"];
        /** 编辑用户（只更新出现的字段） */
        put: operations["updateUser"];
        post?: never;
        /** 删除用户（软删除；不能删除自己或平台管理员） */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重置密码（不传则使用系统缺省密码；该用户所有会话失效） */
        post: operations["resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        /** 分配角色（整体替换） */
        put: operations["assignUserRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/users/import-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载导入模板（xlsx） */
        get: operations["getUserImportTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/users/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Excel 批量导入用户
         * @description 列：用户名*、姓名*、手机号、邮箱、工号、部门名称、角色代码（多个用逗号）。逐行校验，返回成功数与失败明细；密码为系统缺省密码。
         */
        post: operations["importUsers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/users/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出用户（xlsx，支持与列表相同的筛选） */
        get: operations["exportUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/depts/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 部门树（整棵，含人数） */
        get: operations["getDeptTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/depts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 部门平铺列表 */
        get: operations["listDepts"];
        put?: never;
        /** 新建部门 */
        post: operations["createDept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/depts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** 部门详情 */
        get: operations["getDept"];
        /** 编辑部门（可改 parent_id 实现移动；不能移到自己的子树下） */
        put: operations["updateDept"];
        post?: never;
        /** 删除部门（有子部门或在职用户时拒绝） */
        delete: operations["deleteDept"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 角色列表（分页） */
        get: operations["listRoles"];
        put?: never;
        /** 新建角色 */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/roles/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 角色简表（下拉用，本租户全部） */
        get: operations["listRoleOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** 角色详情（含权限码） */
        get: operations["getRole"];
        /** 编辑角色（内置角色只能改名称/描述） */
        put: operations["updateRole"];
        post?: never;
        /** 删除角色（内置角色或仍有用户持有时拒绝） */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/roles/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        /** 设置角色权限（整体替换；非平台租户不能包含平台专属权限；持有者权限缓存立即失效） */
        put: operations["setRolePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/permissions/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 权限点树（菜单为父节点，动作为叶子；非平台租户不返回平台专属权限） */
        get: operations["getPermissionTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 租户列表（平台管理员） */
        get: operations["listTenants"];
        put?: never;
        /** 新建租户（自动创建内置角色与租户管理员账号） */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** 租户详情（含用户数/部门数） */
        get: operations["getTenant"];
        /** 编辑租户（停用时该租户所有用户会话失效） */
        put: operations["updateTenant"];
        post?: never;
        /** 停用租户（不物理删除；平台租户不可停用） */
        delete: operations["disableTenant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/dict-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 字典类型列表（全局 + 本租户） */
        get: operations["listDictTypes"];
        put?: never;
        /** 新建字典类型（超级管理员未指定租户时创建全局字典） */
        post: operations["createDictType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/dict-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** 字典类型详情（含条目） */
        get: operations["getDictType"];
        /** 编辑字典类型（系统字典只能改名称/描述；全局字典仅超级管理员可改） */
        put: operations["updateDictType"];
        post?: never;
        /** 删除字典类型及其条目（系统字典拒绝） */
        delete: operations["deleteDictType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/dict-types/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新增字典条目 */
        post: operations["createDictItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/dict-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        /** 编辑字典条目 */
        put: operations["updateDictItem"];
        post?: never;
        /** 删除字典条目 */
        delete: operations["deleteDictItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/dicts/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按类型代码取启用条目（任意登录用户；租户字典覆盖同名全局字典） */
        get: operations["getDictByCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 参数列表（本租户生效值：租户覆盖优先，否则全局缺省） */
        get: operations["listParams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/params/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 设置参数值（普通租户写租户覆盖；超级管理员未指定 X-Tenant-ID 时写全局缺省） */
        put: operations["setParam"];
        post?: never;
        /** 删除租户覆盖值，恢复全局缺省（全局缺省不可删除） */
        delete: operations["resetParam"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审计日志查询（只读） */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/audit-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** 审计日志详情（含 before/after） */
        get: operations["getAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/notification-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 通知模板列表（全局 + 本租户） */
        get: operations["listTemplates"];
        put?: never;
        /** 新建通知模板 */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/notification-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** 模板详情 */
        get: operations["getTemplate"];
        /** 编辑模板 */
        put: operations["updateTemplate"];
        post?: never;
        /** 删除模板 */
        delete: operations["deleteTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            /** @description 0 成功；40000 参数错误；40100 未认证；40300 无权限；40400 不存在；40900 冲突；50000 内部错误 */
            code: number;
            message: string;
            request_id?: string;
        };
        Page: {
            items: unknown[];
            total: number;
            page: number;
            pageSize: number;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
            env: string;
            uptime_seconds: number;
        };
        Ready: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks: {
                [key: string]: string;
            };
        };
        LoginRequest: {
            username: string;
            password: string;
            /** @description 同名用户存在于多个租户时必填 */
            tenant_code?: string;
        };
        TokenPair: {
            access_token: string;
            /** Format: date-time */
            expires_at: string;
            refresh_token: string;
        };
        LoginResponse: components["schemas"]["TokenPair"] & {
            user: components["schemas"]["Profile"];
        };
        TenantBrief: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
        };
        RoleBrief: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
        };
        MenuNode: {
            /** @example system.user */
            code: string;
            name: string;
            /** @example /system/users */
            path: string;
            /** @description lucide 图标名 */
            icon?: string;
            children?: components["schemas"]["MenuNode"][];
        };
        Profile: {
            /** Format: uuid */
            id: string;
            username: string;
            name: string;
            phone?: string | null;
            email?: string | null;
            avatar_url?: string | null;
            is_super: boolean;
            /** Format: uuid */
            dept_id?: string | null;
            dept_name?: string | null;
            tenant: components["schemas"]["TenantBrief"];
            roles: components["schemas"]["RoleBrief"][];
            /** @description 权限码集合，前端据此控制按钮 */
            permissions: string[];
            menus: components["schemas"]["MenuNode"][];
            /** Format: date-time */
            last_login_at?: string | null;
        };
        /** @enum {string} */
        UserStatus: "active" | "disabled" | "locked";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            dept_id?: string | null;
            dept_name?: string | null;
            username: string;
            name: string;
            phone?: string | null;
            email?: string | null;
            employee_no?: string | null;
            avatar_url?: string | null;
            status: components["schemas"]["UserStatus"];
            is_super: boolean;
            /** Format: date-time */
            last_login_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            roles: components["schemas"]["RoleBrief"][];
        };
        UserCreate: {
            username: string;
            name: string;
            /** @description 留空使用系统缺省密码 */
            password?: string;
            phone?: string;
            /** Format: email */
            email?: string;
            employee_no?: string;
            /** Format: uuid */
            dept_id?: string;
            role_ids?: string[];
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        /** @description 只更新出现的字段；`clear_dept=true` 清空部门 */
        UserUpdate: {
            name?: string;
            phone?: string;
            /** Format: email */
            email?: string;
            employee_no?: string;
            avatar_url?: string;
            /** Format: uuid */
            dept_id?: string;
            clear_dept?: boolean;
            status?: components["schemas"]["UserStatus"];
        };
        ImportResult: {
            total: number;
            success: number;
            failed: number;
            errors: {
                /** @description Excel 行号（从 2 起） */
                row: number;
                username?: string;
                message: string;
            }[];
        };
        Dept: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            parent_id?: string | null;
            name: string;
            code?: string | null;
            /** @description 祖先链 /id1/id2/ */
            path: string;
            sort: number;
            /** Format: uuid */
            leader_user_id?: string | null;
            leader_name?: string | null;
            monthly_budget: number;
            /** @enum {string} */
            status: "active" | "disabled";
            /** @description 直属在职用户数 */
            user_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DeptNode: components["schemas"]["Dept"] & {
            children?: components["schemas"]["DeptNode"][];
        };
        DeptCreate: {
            /** Format: uuid */
            parent_id?: string;
            name: string;
            code?: string;
            sort?: number;
            /** Format: uuid */
            leader_user_id?: string;
            monthly_budget?: number;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        DeptUpdate: {
            /** Format: uuid */
            parent_id?: string;
            /** @description 置为根部门 */
            clear_parent?: boolean;
            name?: string;
            code?: string;
            sort?: number;
            /** Format: uuid */
            leader_user_id?: string;
            clear_leader?: boolean;
            monthly_budget?: number;
            /** @enum {string} */
            status?: "active" | "disabled";
        };
        Role: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description null 为平台级角色
             */
            tenant_id?: string | null;
            code: string;
            name: string;
            description?: string | null;
            is_system: boolean;
            permissions: string[];
            user_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RoleCreate: {
            code: string;
            name: string;
            description?: string;
            permissions?: string[];
        };
        RoleUpdate: {
            name?: string;
            description?: string;
        };
        PermissionNode: {
            code: string;
            name: string;
            /** @enum {string} */
            type: "menu" | "action";
            path?: string;
            icon?: string;
            children?: components["schemas"]["PermissionNode"][];
        };
        Tenant: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            license_no?: string | null;
            contact_name?: string | null;
            contact_phone?: string | null;
            /** @enum {string} */
            status: "active" | "disabled";
            is_platform: boolean;
            /** Format: date-time */
            expires_at?: string | null;
            user_count: number;
            dept_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TenantCreate: {
            code: string;
            name: string;
            license_no?: string;
            contact_name?: string;
            contact_phone?: string;
            /** Format: date-time */
            expires_at?: string;
            /** @description 租户管理员用户名 */
            admin_username: string;
            /** @description 留空使用系统缺省密码 */
            admin_password?: string;
            /** @default 管理员 */
            admin_name: string;
        };
        TenantUpdate: {
            name?: string;
            license_no?: string;
            contact_name?: string;
            contact_phone?: string;
            /** @enum {string} */
            status?: "active" | "disabled";
            /** Format: date-time */
            expires_at?: string;
            clear_expires?: boolean;
        };
        DictType: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id?: string | null;
            is_global: boolean;
            code: string;
            name: string;
            description?: string | null;
            is_system: boolean;
            /** @description 列表接口不返回 */
            items: components["schemas"]["DictItem"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DictTypeCreate: {
            code: string;
            name: string;
            description?: string;
            items?: components["schemas"]["DictItemCreate"][];
        };
        DictTypeUpdate: {
            name?: string;
            description?: string;
        };
        DictItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            dict_type_id: string;
            label: string;
            value: string;
            sort: number;
            color?: string | null;
            /** @enum {string} */
            status: "active" | "disabled";
            extra: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DictItemCreate: {
            label: string;
            value: string;
            sort?: number;
            color?: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
            extra?: {
                [key: string]: unknown;
            };
        };
        DictItemUpdate: {
            label?: string;
            value?: string;
            sort?: number;
            color?: string;
            /** @enum {string} */
            status?: "active" | "disabled";
            extra?: {
                [key: string]: unknown;
            };
        };
        Param: {
            key: string;
            value: string;
            /** @enum {string} */
            value_type: "string" | "int" | "float" | "bool" | "json";
            description?: string | null;
            is_public: boolean;
            /**
             * @description 当前生效值来源
             * @enum {string}
             */
            source: "global" | "tenant";
            /** @description 全局缺省值（source=tenant 时有意义） */
            global_value?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        ParamUpdate: {
            /** @description 按 value_type 校验 */
            value: string;
            description?: string;
        };
        AuditLog: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            tenant_id?: string | null;
            /** Format: uuid */
            user_id?: string | null;
            username?: string | null;
            action: string;
            module: string;
            target_type?: string | null;
            target_id?: string | null;
            summary?: string | null;
            /** @description 详情接口返回 */
            before?: Record<string, never> | unknown[] | null;
            /** @description 详情接口返回 */
            after?: Record<string, never> | unknown[] | null;
            method: string;
            path: string;
            status: number;
            ip?: string | null;
            user_agent?: string | null;
            request_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        NotifyChannel: "inapp" | "wechat" | "sms";
        Template: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id?: string | null;
            is_global: boolean;
            /** @example approval.submitted */
            code: string;
            channel: components["schemas"]["NotifyChannel"];
            title: string;
            /** @description 支持 {{变量}} 占位 */
            content: string;
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TemplateCreate: {
            code: string;
            channel: components["schemas"]["NotifyChannel"];
            title: string;
            content: string;
            /** @default true */
            enabled: boolean;
        };
        TemplateUpdate: {
            title?: string;
            content?: string;
            enabled?: boolean;
        };
    };
    responses: {
        /** @description 成功（data 为简单对象或缺省） */
        OK: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description 错误信封 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description 存活 */
        Health: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Health"];
                };
            };
        };
        /** @description 就绪状态 */
        Ready: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Ready"];
                };
            };
        };
        /** @description 令牌对 */
        TokenPair: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["TokenPair"];
                };
            };
        };
        /** @description 用户 */
        User: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["User"];
                };
            };
        };
        /** @description 用户分页 */
        UserPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Page"] & {
                        items?: components["schemas"]["User"][];
                    };
                };
            };
        };
        /** @description 部门 */
        Dept: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Dept"];
                };
            };
        };
        /** @description 角色 */
        Role: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Role"];
                };
            };
        };
        /** @description 角色分页 */
        RolePage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Page"] & {
                        items?: components["schemas"]["Role"][];
                    };
                };
            };
        };
        /** @description 租户 */
        Tenant: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Tenant"];
                };
            };
        };
        /** @description 租户分页 */
        TenantPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Page"] & {
                        items?: components["schemas"]["Tenant"][];
                    };
                };
            };
        };
        /** @description 字典类型 */
        DictType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["DictType"];
                };
            };
        };
        /** @description 字典类型分页 */
        DictTypePage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Page"] & {
                        items?: components["schemas"]["DictType"][];
                    };
                };
            };
        };
        /** @description 字典条目 */
        DictItem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["DictItem"];
                };
            };
        };
        /** @description 审计日志分页（列表项不含 before/after） */
        AuditLogPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Page"] & {
                        items?: components["schemas"]["AuditLog"][];
                    };
                };
            };
        };
        /** @description 通知模板 */
        Template: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Template"];
                };
            };
        };
        /** @description 通知模板分页 */
        TemplatePage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Page"] & {
                        items?: components["schemas"]["Template"][];
                    };
                };
            };
        };
    };
    parameters: {
        id: string;
        page: number;
        pageSize: number;
        /** @description 排序字段，前缀 `-` 表示降序 */
        sort: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ready"];
            503: components["responses"]["Ready"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["LoginResponse"];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            200: components["responses"]["TokenPair"];
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    refresh_token?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["OK"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Profile"];
                    };
                };
            };
        };
    };
    getMenus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 菜单树 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["MenuNode"][];
                    };
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    old_password: string;
                    /** @description 至少 8 位，含字母和数字 */
                    new_password: string;
                };
            };
        };
        responses: {
            200: components["responses"]["OK"];
            400: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description 排序字段，前缀 `-` 表示降序 */
                sort?: components["parameters"]["sort"];
                /** @description 用户名/姓名/手机号/工号 模糊 */
                keyword?: string;
                /** @description 含子部门 */
                dept_id?: string;
                status?: components["schemas"]["UserStatus"];
                role_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["UserPage"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            201: components["responses"]["User"];
            409: components["responses"]["Error"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["User"];
            404: components["responses"]["Error"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            200: components["responses"]["User"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
        };
    };
    resetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    password?: string;
                };
            };
        };
        responses: {
            /** @description 返回一次明文密码供管理员告知 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            password?: string;
                        };
                    };
                };
            };
        };
    };
    assignUserRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role_ids: string[];
                };
            };
        };
        responses: {
            200: components["responses"]["User"];
        };
    };
    getUserImportTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description xlsx 文件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    importUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 导入结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ImportResult"];
                    };
                };
            };
        };
    };
    exportUsers: {
        parameters: {
            query?: {
                keyword?: string;
                dept_id?: string;
                status?: components["schemas"]["UserStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description xlsx 文件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    getDeptTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 部门树 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["DeptNode"][];
                    };
                };
            };
        };
    };
    listDepts: {
        parameters: {
            query?: {
                keyword?: string;
                status?: "active" | "disabled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 列表（不分页） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Dept"][];
                    };
                };
            };
        };
    };
    createDept: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeptCreate"];
            };
        };
        responses: {
            201: components["responses"]["Dept"];
        };
    };
    getDept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Dept"];
        };
    };
    updateDept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeptUpdate"];
            };
        };
        responses: {
            200: components["responses"]["Dept"];
        };
    };
    deleteDept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
            409: components["responses"]["Error"];
        };
    };
    listRoles: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description 排序字段，前缀 `-` 表示降序 */
                sort?: components["parameters"]["sort"];
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RolePage"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            201: components["responses"]["Role"];
        };
    };
    listRoleOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色简表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["RoleBrief"][];
                    };
                };
            };
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Role"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            200: components["responses"]["Role"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
            409: components["responses"]["Error"];
        };
    };
    setRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    permissions: string[];
                };
            };
        };
        responses: {
            200: components["responses"]["Role"];
        };
    };
    getPermissionTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 权限树 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["PermissionNode"][];
                    };
                };
            };
        };
    };
    listTenants: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description 排序字段，前缀 `-` 表示降序 */
                sort?: components["parameters"]["sort"];
                keyword?: string;
                status?: "active" | "disabled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TenantPage"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreate"];
            };
        };
        responses: {
            201: components["responses"]["Tenant"];
        };
    };
    getTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Tenant"];
        };
    };
    updateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUpdate"];
            };
        };
        responses: {
            200: components["responses"]["Tenant"];
        };
    };
    disableTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
        };
    };
    listDictTypes: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                pageSize?: components["parameters"]["pageSize"];
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DictTypePage"];
        };
    };
    createDictType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictTypeCreate"];
            };
        };
        responses: {
            201: components["responses"]["DictType"];
        };
    };
    getDictType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DictType"];
        };
    };
    updateDictType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictTypeUpdate"];
            };
        };
        responses: {
            200: components["responses"]["DictType"];
        };
    };
    deleteDictType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
        };
    };
    createDictItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictItemCreate"];
            };
        };
        responses: {
            201: components["responses"]["DictItem"];
        };
    };
    updateDictItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictItemUpdate"];
            };
        };
        responses: {
            200: components["responses"]["DictItem"];
        };
    };
    deleteDictItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
        };
    };
    getDictByCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 条目列表（按 sort 升序） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["DictItem"][];
                    };
                };
            };
        };
    };
    listParams: {
        parameters: {
            query?: {
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 参数列表（不分页） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Param"][];
                    };
                };
            };
        };
    };
    setParam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParamUpdate"];
            };
        };
        responses: {
            /** @description 更新后的参数 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Param"];
                    };
                };
            };
        };
    };
    resetParam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                pageSize?: components["parameters"]["pageSize"];
                user_id?: string;
                username?: string;
                module?: string;
                action?: string;
                target_id?: string;
                /** @description summary/path 模糊 */
                keyword?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuditLogPage"];
        };
    };
    getAuditLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AuditLog"];
                    };
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                pageSize?: components["parameters"]["pageSize"];
                keyword?: string;
                channel?: components["schemas"]["NotifyChannel"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TemplatePage"];
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            201: components["responses"]["Template"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Template"];
        };
    };
    updateTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdate"];
            };
        };
        responses: {
            200: components["responses"]["Template"];
        };
    };
    deleteTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OK"];
        };
    };
}
